import { Router } from "express";
import authController from "../controllers/auth.controller";
const authRouter = Router();
authRouter.post("/login", authController.Login);
authRouter.post("/logout", authController.Logout);
authRouter.post("/register", authController.Register);
authRouter.post("/refresh-token", authController.RefreshToken);
authRouter.post("/forgot-password", authController.ForgotPassword);
authRouter.post("/change-password", authController.ResetPassword);
export { authRouter };
