import mongoose, { Schema, Document } from 'mongoose';
import paginate from 'mongoose-paginate-v2';
import Role from '../enums/user.enum';

export interface IUser extends Document {
  email: string;
  password: string; // Hashed password
  role: Role;
  username?: string;
  fullName?: string;
  githubAutoGenerated?: boolean;
  locked?: boolean;
  comparePassword(candidatePassword: string): Promise<boolean>;
}

const UserSchema: Schema = new Schema(
  {
    username: { type: String, required: true, unique: true, sparse: true },
    fullName: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    role: { type: String, enum: Object.values(Role), default: Role.GUEST },
    githubAutoGenerated: { type: Boolean, default: false },
    locked: { type: Boolean, default: false },
  },
  {
    timestamps: true, // Adds createdAt and updatedAt fields automatically
  }
);

// Apply the paginate plugin to the schema
UserSchema.plugin(paginate);

export const User = mongoose.model<IUser>('User', UserSchema);
