import mongoose, { Schema, Document } from 'mongoose';
import Role from '../enums/user.enum';

export interface IUser extends Document {
  email: string;
  password: string; // Hashed password
  role: Role;
  githubAutoGenerated?: boolean;
  comparePassword(candidatePassword: string): Promise<boolean>;
}

const UserSchema: Schema = new Schema(
  {
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    role: { type: String, enum: Object.values(Role), default: Role.GUEST },
    githubAutoGenerated: { type: Boolean, default: false },
  },
  {
    timestamps: true, // Adds createdAt and updatedAt fields automatically
  }
);

export const User = mongoose.model<IUser>('User', UserSchema);
